version: 0.1

env:
  secrets-manager:
    DOCKERHUB_PASS: "/dockerhub/credentials:password"
    DOCKERHUB_USERNAME: "/dockerhub/credentials:username"

phases:
  build:
    commands:
      - echo $DOCKERHUB_USERNAME
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/weather-app-0.0.1-SNAPSHOT.jar