version: 0.1

env:
  secrets-manager:
    DOCKERHUB_PASS: "dockerhub:password"
    DOCKERHUB_USERNAME: "dockerhub:username"

phases:
  build:
    commands:
      - echo $DOCKERHUB_USERNAME
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - docker build -t biplabnayak/weather-app .
      - docker push biplabnayak/weather-app
cache:
  paths:
    - '/root/.m2/**/*'
artifacts:
  files:
    - target/weather-app-0.0.1-SNAPSHOT.jar
